# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eaa340f53b37642c96606c1fa503d7510c8897f737153203f3cd53e65f676eace7e048c4d35183819bf41afc3c7f4f09ffd5c4ecab77ce4f0345491163d0136

test:
  secret_key_base: 8f456943a5ab6a37851b23073b2ff6b3a6fc948784094d505db551a9cac2164a5c95cf110d44d324424a3779d3aee116c1c7c5dca0696661cfeac42aa30881cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
